### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by bevsxyz** [chathika/NL4Py#14]
Hi,
The documentation seems to be outdated. Also I am unable to find the latest version NL4Py 0.6.0, here at the repo.
This command `nl4py.startServer(netlogo_home)` seems to be depreciated. 
I tried `nl4py.initialize(netlogo_home)` instead as pointed from the error log, but Im not in luck.
Here is the error log from jupyter notebook for initialize.
```---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-5dfea99c9d00> in <module>
----> 1 nl4py.initialize("/home/bevan/software/NetLogo_6.1.1/")

~/.local/lib/python3.8/site-packages/nl4py/__init__.py in initialize(netlogo_home)
     36     '''
     37     global server_starter
---> 38     server_starter = NetLogoControllerServerStarter(netlogo_home,SERVER_PORT)
     39     global netlogoWorkspaceFactory
     40     netlogoWorkspaceFactory = NetLogoWorkspaceFactory(SERVER_PORT)

~/.local/lib/python3.8/site-packages/nl4py/NetLogoControllerServerStarter.py in __init__(self, netlogo_home, server_port)
     38         self.SERVER_PATH = pkg_resources.resource_filename('nl4py', 'nl4pyServer/')
     39         self.server_port = server_port
---> 40         self.init_server()
     41         self.jg = JavaGateway(gateway_parameters=GatewayParameters(auto_convert=True,port=self.server_port))
     42 

~/.local/lib/python3.8/site-packages/nl4py/NetLogoControllerServerStarter.py in init_server(self)
     48         '''
     49 
---> 50         py4j_jar_path = glob.glob(os.path.join(self.SERVER_PATH, "py4j*.jar"))[0]
     51         __server_name = "nl4py.server.NetLogoControllerServer"
     52         nl_path = ""

IndexError: list index out of range
```
Your examples need an update I think 😺

**Comment by chathika** [comment]
Thank you for pointing this out @chain-ed-reaction . Yes, there was a bug in v0.6.0. The error you are seeing is due to NL4Py not finding the dependency `py4j0.10.6.jar`. I have released [v0.7.0](https://pypi.org/project/NL4Py/0.7.0/) which should have fixed this issue. 

Also, to avoid such mistakes in the future, I have automated unittest workflows, for which you should see status badges on the README now.

And yes, you are correct, please use `nl4py.initialize(netlogo_home)` instead of `nl4py.startServer(netlogo_home)` . I've updated all of the examples and README accordingly.
