### ISSUE TITLE
getting param values

### ISSUE THREAD

**Issue by wmirecon** [chathika/NL4Py#4]
Is there a function/method to see default or set parameter values, something other than the range of options? If not, I think this would be a good addition.

**Comment by chathika** [comment]
@wmirecon thanks for the question. 

Yes you can use the following functions to get parameter names from the NetLogo interface and their default ranges: 
```nl4py.NetLogoHeadlessWorkspace.getParamNames()```
```nl4py.NetLogoHeadlessWorkspace.getParamRanges()```

You can also use the following to randomly initialize the parameters:
```nl4py.NetLogoHeadlessWorkspace.setParamsRandom()```

These functions are borrowed from BehaviorSearch and may be slower than setting it yourself using ```nl4py.NetLogoHeadlessWorkspace.command()``` since they will read the NetLogo model file. 

example: ```n.command("set param1 100")```
when n is your HeadlessWorkspace object.

If you run the model without setting parameters, NetLogo should use the default parameter settings you saved your model file with

**Comment by wmirecon** [comment]
Yes, I'm familiar w/ all of that.

What I'm thinking of is finding out if params are initialized w/ default values when I open the model. As you know, the SocialSim NL template has rather a lot of input params and if I want to vary the value of just one of them, it would be helpful to set just that one and let the others remain default. But I couldn't confirm if the default values had been assigned or not when I opened in an NL4Py headless workspace. It would be rather helpful to be able to check how params are initalized w/out having to set each and everyone of them.

Thanks

**Comment by chathika** [comment]
@wmirecon ok, I understand the requirement now. There is no explicit function in NL4Py at the moment to get a single parameter value. I can add this as a feature. 

Meanwhile, you could use the ```report``` function to do this as well:

```python 
import nl4py
nl4py.startServer("C:/Program Files/NetLogo 6.0.2")
n = nl4py.newNetLogoHeadlessWorkspace()
n.openModel("C:/Program Files/NetLogo 6.0.2/app/models/Sample Models/Biology/Wolf Sheep Predation.nlogo")
names = n.getParamNames()
for name in names:
    print(name + " " + str(n.report(name)))
nl4py.stopServer()
```

Hope this helps!

**Comment by wmirecon** [comment]
Thanks, @chathika !

**Comment by deamonpog** [comment]
When you open the model, the headless workspace is set to the default values which are stored in the model file.
You could check/set the default values when you load the model (before making any other changes) to ensure this. Following code might help you with this:

```python
import nl4py
nl4py.startServer("C:/Program Files/NetLogo 6.0.2")
n = nl4py.newNetLogoHeadlessWorkspace()
n.openModel("C:/Program Files/NetLogo 6.0.2/app/models/Sample Models/Biology/Wolf Sheep Predation.nlogo")
names = n.getParamNames()

# A dictionary to store preferred values for a subset (or all) of parameters
defaults = {'initial-number-sheep':100,'initial-number-wolves':50}

print('Parameter values retrieved from the Model File:')
for name in names:
	print(name + " " + str(n.report(name)))

print('Setting the preferred parameter values...')
for name in names:
	if name in defaults.keys():
		n.command('set {} {}'.format(name, defaults[name]))

print('Current parameter values:')
for name in names:
	print(name + " " + str(n.report(name)))

# Rest of your code.....

```
---
Additionally, be mindful that doing something such as :
```python
if defaults[name] != n.report(name):
    print("{} not set to default!".format(name))
```
Will **NOT** work for **ALL** parameter types since for example a comparison of a floating point value using double-equals ( `==` ) operator is not advisable due to floating point errors.
