### ISSUE TITLE
Not work if having extensions

### ISSUE THREAD

**Issue by NedaMarvasti** [chathika/NL4Py#9]
Hi,
I have a netlogo model in which I have the following extension:
extensions [rnd stats csv matrix py]

when i call the go command using nl4py I get netlogo exception. But if I remove the extension and corresponding usage there will be no error.
would you please help me on this issue? I need those extensions in the model.
Thanks.

**Comment by NedaMarvasti** [comment]
Hi, I checked again and problem is with extensions [stats py] which I used to produce a random variable from Beta distribution.

to setup-beta-python
  py:setup py:python3
  (py:run
    "from scipy.stats import beta")
end

and then let value py:runresult "beta.rvs(1, 1, size=1)"

**Comment by lfwells** [comment]
I've had luck with getting extensions working by copying the extensions folder over to be in the same location as where I'm calling the nl4py code.

**Comment by deamonpog** [comment]
@NedaMarvasti : This issue has been with NL4Py v0.5.11 for all extensions.
Please upgrade your NL4Py Installation to the latest by using the command `pip install --upgrade nl4py` on your terminal/command prompt.
This was caused, since system property `org.nlogo.preferHeadless` was not set to `true `as required, which is now fixed the NL4Py v0.5.11
@lfwells: Extensions should work with no changes to the directory structure. Copying over the extension files should not be required anymore.
